FROM golang:1.19 AS BUILDER 

WORKDIR /app

COPY . .

RUN go mod download
RUN make build-subscriber


FROM alpine:3.15

WORKDIR /app

COPY --from=BUILDER /app/bin/subscriber ./

CMD [ "./subscriber" ]