version: "3.7"
services:
  dev_db:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: users-microservice
    ports:
      - 27017:27017
    # volumes:
    #   - ./init-db.js:/docker-entrypoint-initdb.d/init.js
